version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "lkp-db"
      POSTGRES_USER: "eos"
      POSTGRES_PASSWORD: "eos123"
    ports:
      - "5432:5432"
    volumes:
      - lkp-data:/var/lib/postgresql/data/

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev

volumes:
  lkp-data: